version: '3'
services:
  api:
    build: ./docker/go
    ports:
      - '3003:3003'
    volumes:
      - '.:/go/src/github.com/ukkary/repo_name'
    command: go run app/main.go
    depends_on:
      - db
    links:
      - db
  db:
    build: ./docker/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass 
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql